update images

diff --git a/core/algorithm-builder/dockerfile/Dockerfile b/core/algorithm-builder/dockerfile/Dockerfile
--- a/core/algorithm-builder/dockerfile/Dockerfile
+++ b/core/algorithm-builder/dockerfile/Dockerfile
@@ -9,14 +9,14 @@ ENV DOCKER_ARCH 'x86_64'
 RUN set -eux; \
 	\
 	if ! wget -O docker.tgz "https://download.docker.com/linux/static/${DOCKER_CHANNEL}/${DOCKER_ARCH}/docker-${DOCKER_VERSION}.tgz"; then \
-		echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${DOCKER_ARCH}'"; \
-		exit 1; \
+	echo >&2 "error: failed to download 'docker-${DOCKER_VERSION}' from '${DOCKER_CHANNEL}' for '${DOCKER_ARCH}'"; \
+	exit 1; \
 	fi; \
 	\
 	tar --extract \
-		--file docker.tgz \
-		--strip-components 1 \
-		--directory /usr/local/bin/ \
+	--file docker.tgz \
+	--strip-components 1 \
+	--directory /usr/local/bin/ \
 	; \
 	rm docker.tgz; \
 	\
